name: Keep Streamlit Alive

on:
  schedule:
    # يعمل تلقائياً كل 7 ساعات
    - cron: '0 */7 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -fsSL --retry 3 "https://datapilot-analytics.streamlit.app"
